# Generated by Django 5.2.8 on 2025-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance'), ('broken', 'Broken'), ('out of service', 'Out of Service')], default='available', max_length=20),
        ),
    ]
