# Generated by Django 5.2.8 on 2025-11-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_rename_emergency_contact_patient_emergency_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_status', models.CharField(choices=[('stable', 'Stable'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('bp', models.CharField(blank=True, max_length=8)),
                ('oxygen', models.IntegerField(blank=True, null=True)),
                ('other_vitals', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
