# Generated by Django 5.2.8 on 2025-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_current_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxygen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='recovery_status',
            field=models.CharField(choices=[('critical', 'Critical'), ('stable', 'Stable'), ('recovering', 'Recovering')], default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=30),
        ),
    ]
