# Generated by Django 5.2.8 on 2025-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_bp_patient_oxygen_patient_recovery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recovery_status',
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
