# Generated by Django 5.2.8 on 2025-11-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_bp_remove_patient_oxygen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact',
            new_name='emergency_contact_phone',
        ),
    ]
