# Generated by Django 5.2.8 on 2025-11-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('scheduled', 'Scheduled'), ('transfer', 'Transfer')], max_length=50)),
                ('admission_date_time', models.DateTimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('bed_number', models.CharField(max_length=20)),
                ('chief_complaint', models.TextField()),
                ('vital_signs_bp', models.CharField(blank=True, max_length=20)),
                ('vital_signs_hr', models.IntegerField(blank=True, null=True)),
                ('vital_signs_temperature', models.FloatField(blank=True, null=True)),
                ('vital_signs_rr', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-admission_date_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date_time', models.DateTimeField(auto_now_add=True)),
                ('bp', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patient')),
            ],
            options={
                'ordering': ['-observation_date_time'],
            },
        ),
    ]
